name: Container Image Toolkit Action
description: Sync images from source registry to target registry.
branding:
  icon: refresh-cw
  color: blue
inputs:
  version:
    description: "Version of the container-image-toolkit"
    required: false
    default: "latest"
  args:
    description: 'Arguments to pass to container-image-toolkit'
    required: false
  workdir:
    description: 'Working directory (below repository root)'
    default: '.'
    required: false
  install-only:
    description: 'Just install container-image-toolkit'
    default: 'false'
    required: false
outputs:
  version:
    description: "Version of the container-image-toolkit"

runs:
  using: 'composite'
  steps:
    - name: test
      run: |
        echo "test"
        echo "${{ inputs.vesion }}"
        echo "${{ inputs.args }}
        echo "${{ inputs.workdir }}
        echo "${{ inputs.install-only }}

#  image: 'Dockerfile'
#  args:
#    - ${{ inputs.target-registry-url }}
#    - ${{ inputs.target-registry-namespace }}
#    - ${{ inputs.docker-username }}
#    - ${{ inputs.docker-password }}